### ISSUE TITLE
Using too much br tags that aren't needed.  

### ISSUE THREAD

**Issue by orjwan98** [FACK1/photoBook#27]
https://github.com/FACK1/photoBook/blob/7c35aa0617306caf39774cf7f45a741f78458a3e/index.htm#L29-L38

In those lines you use too much br tags. I assume you did that to fit the container, which could have been done in a cleaner and easier to maintain way using css. If you feel like I don't get the idea behind using it, please feel free to correct me.

**Comment by safaaamro** [comment]
`BR` tag is only for newlining content.
