### ISSUE TITLE
Using inline CSS (instead of External CSS)

### ISSUE THREAD

**Issue by orjwan98** [FACK1/photoBook#35]
https://github.com/FACK1/photoBook/blob/7c35aa0617306caf39774cf7f45a741f78458a3e/index.htm#L15-L18

In those lines you are applying the style inside the tag which is considered bad practice for reasons, one of which is (it's VERY hard to maintain and track down). Now to give you an example, assume you have a huge project of multiple pages and the client asked for a change? You would have to skim through hundreds of lines of code to find your target and if you applied the same style throughout it would be a nightmare to change each and everyone.

Using classes and Ids (in an External css file) would make it much easier and more helpful to do so :)

**Comment by safaaamro** [comment]
For images like logos, it's better I think to add dimensions in html not css, because html loads before css, and logos are on the top of the page, and it's only one logo!
